REPORT-231: Melhoria de Qualidade do HIV - 2022 Categoria 14 – Supressão Viral
FriendsInGlobalHealth/openmrs-module-eptsreports pull request #187
Opened 2022-03-10 16:58 UTC by nelsonhomo

2022-03-16 09:11 UTC, Guimino requested changes

2022-03-16 09:11 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory15CohortQueries.java
> +        String.format("MQ - PatientsWhoAreNewlyEnrolledOnARTByAgeUsingAgeRange", startAge, endAge));
@emaposse  qual é  a necessidade de usares String.format aqui?

2022-03-16 09:11 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "findPatientsWithClinicalConsultationAndARTStartDateGreaterThanTwentyOneMonths");
@emaposse  Peço para no SetName escrever o proposito da CohortDefinition para deixar o log mais legivel

2022-03-16 09:11 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "findPatientsRegisteredInOneMDSForStablePatientsAndHadCVBetweenTwelveAndEigtheenMonthsAfterCVLessThan1000");
@emaposse  Peço para no SetName escrever o proposito da CohortDefinition para deixar o log mais legivel

2022-03-16 09:11 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +    definition.setName("patientsInDSDWithViralSupressionDenominatorCategory14Indicator");
@emaposse  Peço para no SetName escrever o proposito da CohortDefinition para deixar o log mais legivel

2022-03-16 09:11 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +    definition.setName("patientsInDSDWithViralSupressionNumeratorCategory14Indicator");
@emaposse  Peço para no SetName escrever o proposito da CohortDefinition para deixar o log mais legivel

2022-03-16 19:43 UTC, emaposse commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +    definition.setName("patientsInDSDWithViralSupressionNumeratorCategory14Indicator");
done

2022-03-16 19:43 UTC, emaposse commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +    definition.setName("patientsInDSDWithViralSupressionDenominatorCategory14Indicator");
done

2022-03-16 19:43 UTC, emaposse commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "findPatientsRegisteredInOneMDSForStablePatientsAndHadCVBetweenTwelveAndEigtheenMonthsAfterCVLessThan1000");
done

2022-03-16 19:43 UTC, emaposse commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "findPatientsWithClinicalConsultationAndARTStartDateGreaterThanTwentyOneMonths");
done

2022-03-16 19:44 UTC, emaposse commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory15CohortQueries.java
> +        String.format("MQ - PatientsWhoAreNewlyEnrolledOnARTByAgeUsingAgeRange", startAge, endAge));
done

2022-03-17 11:13 UTC, Guimino requested changes
@nelsonhomo  Peço para aplicares os fixes aos cosméticos que solicitei

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Catefory 15 - PatientsWithClinicalConsultationAndARTStartDateGreaterThanTwentyOneMonths");
@emaposse  @nelsonhomo  peço para melhorarem essa descricao **PatientsWithClinicalConsultationAndARTStartDateGreaterThanTwentyOneMonths**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Category 15 - PatientsRegisteredInMDSForStablePatientsWithClinicalConsultationInTheRevisionPeriodInARTMoreThan21Months");
melhorar descricao **PatientsRegisteredInMDSForStablePatientsWithClinicalConsultationInTheRevisionPeriodInARTMoreThan21Months**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Category 15 - PatientsRegisteredInOneMDSForStablePatientsAndHadCVBetweenTwelveAndEigtheenMonthsAfterCVLessThan1000");
melhorar a descricao **PatientsRegisteredInOneMDSForStablePatientsAndHadCVBetweenTwelveAndEigtheenMonthsAfterCVLessThan1000**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "MQ - PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
melhorar a descricao **PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "MQ - PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadResultLessthan1000RegisteredInTheLast12Months");
melhorar a descricao **PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadResultLessthan1000RegisteredInTheLast12Months**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "PregnantWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
Melhorar a descricao **PregnantWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "BreastfeedingWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
Melhorar a descricao **BreastfeedingWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months**

2022-03-17 11:13 UTC, Guimino commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +    definition.setName("MQ - PatientsWhoAreActiveOnArtAndInAtleastOneDSDWithViralSupression");
Melhorar a descricao **PatientsWhoAreActiveOnArtAndInAtleastOneDSDWithViralSupression**

2022-03-17 19:33 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Category 15 - PatientsRegisteredInMDSForStablePatientsWithClinicalConsultationInTheRevisionPeriodInARTMoreThan21Months");
done

2022-03-17 19:33 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Category 15 - PatientsRegisteredInOneMDSForStablePatientsAndHadCVBetweenTwelveAndEigtheenMonthsAfterCVLessThan1000");
done

2022-03-17 19:33 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "MQ - PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
done

2022-03-17 19:33 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "MQ - PatientsWhoHaveMoreThan3MonthsOnArtWithViralLoadResultLessthan1000RegisteredInTheLast12Months");
done

2022-03-17 19:33 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "PregnantWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
done

2022-03-17 19:34 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mq/MQCategory14CohortQueries.java
> +        "BreastfeedingWomanWhoHaveMoreThan3MonthsOnArtWithViralLoadRegisteredInTheLast12Months");
done

2022-03-17 19:34 UTC, nelsonhomo commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/mi/MICategory15CohortQueries.java
> +        "MI Catefory 15 - PatientsWithClinicalConsultationAndARTStartDateGreaterThanTwentyOneMonths");
done

2022-03-18 06:44 UTC, merged